#!/bin/bash -l
#SBATCH --job-name=pytorch_cifar
#SBATCH --output=output.slurm

#SBATCH --time=3-00:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=100000mb
#SBATCH --mail-type=END,FAIL,REQUEUE,STAGE_OUT
#SBATCH --mail-user=qhv200@nyu.edu
#SBATCH --partition=centos7
#SBATCH --nodelist=gpu1
#SBATCH --gres=gpu:4
#SBATCH --share

source activate pytorch2_cpu_py36
cd /gpfsnyu/home/qhv200/pytorch-cifar

OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 python main.py
